# Generated by Django 4.1.7 on 2023-03-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('duration', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('special', models.BooleanField(default=False)),
            ],
        ),
    ]
