# Generated by Django 4.1.7 on 2023-03-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.destination'),
        ),
    ]
